vpc:
  vpc_id: vpc-xxxxxxxx
  region: us-east-1

subnets:
  public:
    - subnet-pub-az1
    - subnet-pub-az2
  private_controller: subnet-admin-xxxx
  application:
    - subnet-app-az1
    - subnet-app-az2
  server:
    - subnet-srv-az1
    - subnet-srv-az2
  microserver: subnet-micro-xxxx

ec2:
  application:
    ami_id: ami-xxxxxxxx
    instance_type: t3.micro
    key_name: mi-key-pair
    security_group_id: sg-xxxxxxxx
  server:
    ami_id: ami-yyyyyyyy
    instance_type: t3.micro
    key_name: mi-key-pair
    security_group_id: sg-xxxxxxxx

load_balancer:
  application_target_group_arn: arn:aws:elasticloadbalancing:...
  server_target_group_arn: arn:aws:elasticloadbalancing:...

kubernetes:
  kubeconfig_path: /ruta/al/kubeconfig
  namespace: default
  deployment_name: microserver-app
  node_port: 30080